apiVersion: v1
kind: Pod
metadata:
  name: keycloak-operator-test
spec:
  restartPolicy: Never
  containers:
  - name: keycloak-operator-test
    image: quay.io/integreatly/keycloak-operator:v1.3.6
    imagePullPolicy: Always
    command: ["/go-test.sh"]
    env:
      - name: TEST_NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
